-- MySQL Script generated by MySQL Workbench
-- sex 03 out 2025 09:50:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermercado` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supermercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermercado` DEFAULT CHARACTER SET utf8 ;
USE `supermercado` ;
USE `supermercado` ;

-- -----------------------------------------------------
-- Table `supermercado`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`tb_categoria` (
  `categoria_id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supermercado`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`tb_produto` (
  `produto_id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto_nome` VARCHAR(255) NOT NULL,
  `produto_preco` FLOAT NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  `produto_foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`produto_id`),
  INDEX `fk_tb_produto_tb_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `supermercado`.`tb_categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supermercado`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`tb_usuario` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(255) NOT NULL,
  `usuario_datanascimento` DATE NOT NULL,
  `usuario_email` VARCHAR(255) NOT NULL,
  `usuario_senha` VARCHAR(255) NOT NULL,
  `usuario_tipo` VARCHAR(1) NOT NULL,
  `usuario_foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supermercado`.`tb_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`tb_estoque` (
  `estoque_id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto_id` INT(11) NOT NULL,
  `estoque_qtd` INT(11) NOT NULL,
  `estoque_data` DATE NOT NULL,
  PRIMARY KEY (`estoque_id`),
  INDEX `fk_tb_estoque_tb_produto_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_estoque_tb_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `supermercado`.`tb_produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supermercado`.`tb_lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermercado`.`tb_lista` (
  `usuario_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`, `produto_id`),
  INDEX `fk_tb_usuario_has_tb_produto_tb_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_produto_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `supermercado`.`tb_produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_produto_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `supermercado`.`tb_usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
